/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './screens/__root'
import { Route as publicLayoutRouteImport } from './screens/(public)/_layout'
import { Route as privateLayoutRouteImport } from './screens/(private)/_layout'
import { Route as publicSignUpRouteImport } from './screens/(public)/sign-up'
import { Route as publicSignInRouteImport } from './screens/(public)/sign-in'
import { Route as publicResetPasswordRouteImport } from './screens/(public)/reset-password'
import { Route as publicForgotPasswordRouteImport } from './screens/(public)/forgot-password'
import { Route as privateOnboardingLayoutRouteImport } from './screens/(private)/onboarding/_layout'
import { Route as privateappLayoutRouteImport } from './screens/(private)/(app)/_layout'
import { Route as privateOnboardingIndexRouteImport } from './screens/(private)/onboarding/index'
import { Route as privateappIndexRouteImport } from './screens/(private)/(app)/index'
import { Route as privateOnboardingWelcomeRouteImport } from './screens/(private)/onboarding/welcome'
import { Route as privateOnboardingVerifyPhoneRouteImport } from './screens/(private)/onboarding/verify-phone'
import { Route as privateOnboardingCreateWorkspaceRouteImport } from './screens/(private)/onboarding/create-workspace'
import { Route as privateappSettingsRouteImport } from './screens/(private)/(app)/settings'
import { Route as privateappCreatorsRouteImport } from './screens/(private)/(app)/creators'
import { Route as privateappCampaignsRouteImport } from './screens/(private)/(app)/campaigns'
import { Route as publicCampaignsCampaignIdInviteRouteImport } from './screens/(public)/campaigns.$campaignId.invite'
import { Route as privateappWorkspaceSettingsRouteImport } from './screens/(private)/(app)/workspace.settings'
import { Route as privateappInfluencerInfluencerIdRouteImport } from './screens/(private)/(app)/influencer.$influencerId'
import { Route as privateappCampaignsNewRouteImport } from './screens/(private)/(app)/campaigns.new'
import { Route as privateappCampaignsCampaignIdRouteImport } from './screens/(private)/(app)/campaigns.$campaignId'
import { Route as privateappCampaignsCampaignIdEditRouteImport } from './screens/(private)/(app)/campaigns.$campaignId.edit'
import { Route as privateappCampaignsCampaignIdInfluencerInfluencerIdRouteImport } from './screens/(private)/(app)/campaigns.$campaignId.influencer.$influencerId'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicResetPasswordRoute = publicResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateOnboardingLayoutRoute = privateOnboardingLayoutRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateappLayoutRoute = privateappLayoutRouteImport.update({
  id: '/(app)',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateOnboardingIndexRoute = privateOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateOnboardingLayoutRoute,
} as any)
const privateappIndexRoute = privateappIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateappLayoutRoute,
} as any)
const privateOnboardingWelcomeRoute =
  privateOnboardingWelcomeRouteImport.update({
    id: '/welcome',
    path: '/welcome',
    getParentRoute: () => privateOnboardingLayoutRoute,
  } as any)
const privateOnboardingVerifyPhoneRoute =
  privateOnboardingVerifyPhoneRouteImport.update({
    id: '/verify-phone',
    path: '/verify-phone',
    getParentRoute: () => privateOnboardingLayoutRoute,
  } as any)
const privateOnboardingCreateWorkspaceRoute =
  privateOnboardingCreateWorkspaceRouteImport.update({
    id: '/create-workspace',
    path: '/create-workspace',
    getParentRoute: () => privateOnboardingLayoutRoute,
  } as any)
const privateappSettingsRoute = privateappSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => privateappLayoutRoute,
} as any)
const privateappCreatorsRoute = privateappCreatorsRouteImport.update({
  id: '/creators',
  path: '/creators',
  getParentRoute: () => privateappLayoutRoute,
} as any)
const privateappCampaignsRoute = privateappCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => privateappLayoutRoute,
} as any)
const publicCampaignsCampaignIdInviteRoute =
  publicCampaignsCampaignIdInviteRouteImport.update({
    id: '/campaigns/$campaignId/invite',
    path: '/campaigns/$campaignId/invite',
    getParentRoute: () => publicLayoutRoute,
  } as any)
const privateappWorkspaceSettingsRoute =
  privateappWorkspaceSettingsRouteImport.update({
    id: '/workspace/settings',
    path: '/workspace/settings',
    getParentRoute: () => privateappLayoutRoute,
  } as any)
const privateappInfluencerInfluencerIdRoute =
  privateappInfluencerInfluencerIdRouteImport.update({
    id: '/influencer/$influencerId',
    path: '/influencer/$influencerId',
    getParentRoute: () => privateappLayoutRoute,
  } as any)
const privateappCampaignsNewRoute = privateappCampaignsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => privateappCampaignsRoute,
} as any)
const privateappCampaignsCampaignIdRoute =
  privateappCampaignsCampaignIdRouteImport.update({
    id: '/$campaignId',
    path: '/$campaignId',
    getParentRoute: () => privateappCampaignsRoute,
  } as any)
const privateappCampaignsCampaignIdEditRoute =
  privateappCampaignsCampaignIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => privateappCampaignsCampaignIdRoute,
  } as any)
const privateappCampaignsCampaignIdInfluencerInfluencerIdRoute =
  privateappCampaignsCampaignIdInfluencerInfluencerIdRouteImport.update({
    id: '/influencer/$influencerId',
    path: '/influencer/$influencerId',
    getParentRoute: () => privateappCampaignsCampaignIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof privateOnboardingLayoutRouteWithChildren
  '/forgot-password': typeof publicForgotPasswordRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/campaigns': typeof privateappCampaignsRouteWithChildren
  '/creators': typeof privateappCreatorsRoute
  '/settings': typeof privateappSettingsRoute
  '/onboarding/create-workspace': typeof privateOnboardingCreateWorkspaceRoute
  '/onboarding/verify-phone': typeof privateOnboardingVerifyPhoneRoute
  '/onboarding/welcome': typeof privateOnboardingWelcomeRoute
  '/': typeof privateappIndexRoute
  '/onboarding/': typeof privateOnboardingIndexRoute
  '/campaigns/$campaignId': typeof privateappCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof privateappCampaignsNewRoute
  '/influencer/$influencerId': typeof privateappInfluencerInfluencerIdRoute
  '/workspace/settings': typeof privateappWorkspaceSettingsRoute
  '/campaigns/$campaignId/invite': typeof publicCampaignsCampaignIdInviteRoute
  '/campaigns/$campaignId/edit': typeof privateappCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/influencer/$influencerId': typeof privateappCampaignsCampaignIdInfluencerInfluencerIdRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/reset-password': typeof publicResetPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/campaigns': typeof privateappCampaignsRouteWithChildren
  '/creators': typeof privateappCreatorsRoute
  '/settings': typeof privateappSettingsRoute
  '/onboarding/create-workspace': typeof privateOnboardingCreateWorkspaceRoute
  '/onboarding/verify-phone': typeof privateOnboardingVerifyPhoneRoute
  '/onboarding/welcome': typeof privateOnboardingWelcomeRoute
  '/': typeof privateappIndexRoute
  '/onboarding': typeof privateOnboardingIndexRoute
  '/campaigns/$campaignId': typeof privateappCampaignsCampaignIdRouteWithChildren
  '/campaigns/new': typeof privateappCampaignsNewRoute
  '/influencer/$influencerId': typeof privateappInfluencerInfluencerIdRoute
  '/workspace/settings': typeof privateappWorkspaceSettingsRoute
  '/campaigns/$campaignId/invite': typeof publicCampaignsCampaignIdInviteRoute
  '/campaigns/$campaignId/edit': typeof privateappCampaignsCampaignIdEditRoute
  '/campaigns/$campaignId/influencer/$influencerId': typeof privateappCampaignsCampaignIdInfluencerInfluencerIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(private)/(app)': typeof privateappLayoutRouteWithChildren
  '/(private)/onboarding': typeof privateOnboardingLayoutRouteWithChildren
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/reset-password': typeof publicResetPasswordRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/(app)/campaigns': typeof privateappCampaignsRouteWithChildren
  '/(private)/(app)/creators': typeof privateappCreatorsRoute
  '/(private)/(app)/settings': typeof privateappSettingsRoute
  '/(private)/onboarding/create-workspace': typeof privateOnboardingCreateWorkspaceRoute
  '/(private)/onboarding/verify-phone': typeof privateOnboardingVerifyPhoneRoute
  '/(private)/onboarding/welcome': typeof privateOnboardingWelcomeRoute
  '/(private)/(app)/': typeof privateappIndexRoute
  '/(private)/onboarding/': typeof privateOnboardingIndexRoute
  '/(private)/(app)/campaigns/$campaignId': typeof privateappCampaignsCampaignIdRouteWithChildren
  '/(private)/(app)/campaigns/new': typeof privateappCampaignsNewRoute
  '/(private)/(app)/influencer/$influencerId': typeof privateappInfluencerInfluencerIdRoute
  '/(private)/(app)/workspace/settings': typeof privateappWorkspaceSettingsRoute
  '/(public)/campaigns/$campaignId/invite': typeof publicCampaignsCampaignIdInviteRoute
  '/(private)/(app)/campaigns/$campaignId/edit': typeof privateappCampaignsCampaignIdEditRoute
  '/(private)/(app)/campaigns/$campaignId/influencer/$influencerId': typeof privateappCampaignsCampaignIdInfluencerInfluencerIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/creators'
    | '/settings'
    | '/onboarding/create-workspace'
    | '/onboarding/verify-phone'
    | '/onboarding/welcome'
    | '/'
    | '/onboarding/'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/influencer/$influencerId'
    | '/workspace/settings'
    | '/campaigns/$campaignId/invite'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/influencer/$influencerId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/reset-password'
    | '/sign-in'
    | '/sign-up'
    | '/campaigns'
    | '/creators'
    | '/settings'
    | '/onboarding/create-workspace'
    | '/onboarding/verify-phone'
    | '/onboarding/welcome'
    | '/'
    | '/onboarding'
    | '/campaigns/$campaignId'
    | '/campaigns/new'
    | '/influencer/$influencerId'
    | '/workspace/settings'
    | '/campaigns/$campaignId/invite'
    | '/campaigns/$campaignId/edit'
    | '/campaigns/$campaignId/influencer/$influencerId'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/(app)'
    | '/(private)/onboarding'
    | '/(public)/forgot-password'
    | '/(public)/reset-password'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/(app)/campaigns'
    | '/(private)/(app)/creators'
    | '/(private)/(app)/settings'
    | '/(private)/onboarding/create-workspace'
    | '/(private)/onboarding/verify-phone'
    | '/(private)/onboarding/welcome'
    | '/(private)/(app)/'
    | '/(private)/onboarding/'
    | '/(private)/(app)/campaigns/$campaignId'
    | '/(private)/(app)/campaigns/new'
    | '/(private)/(app)/influencer/$influencerId'
    | '/(private)/(app)/workspace/settings'
    | '/(public)/campaigns/$campaignId/invite'
    | '/(private)/(app)/campaigns/$campaignId/edit'
    | '/(private)/(app)/campaigns/$campaignId/influencer/$influencerId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/reset-password': {
      id: '/(public)/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof publicResetPasswordRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/onboarding': {
      id: '/(private)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof privateOnboardingLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/(app)': {
      id: '/(private)/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateappLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/onboarding/': {
      id: '/(private)/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof privateOnboardingIndexRouteImport
      parentRoute: typeof privateOnboardingLayoutRoute
    }
    '/(private)/(app)/': {
      id: '/(private)/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateappIndexRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(private)/onboarding/welcome': {
      id: '/(private)/onboarding/welcome'
      path: '/welcome'
      fullPath: '/onboarding/welcome'
      preLoaderRoute: typeof privateOnboardingWelcomeRouteImport
      parentRoute: typeof privateOnboardingLayoutRoute
    }
    '/(private)/onboarding/verify-phone': {
      id: '/(private)/onboarding/verify-phone'
      path: '/verify-phone'
      fullPath: '/onboarding/verify-phone'
      preLoaderRoute: typeof privateOnboardingVerifyPhoneRouteImport
      parentRoute: typeof privateOnboardingLayoutRoute
    }
    '/(private)/onboarding/create-workspace': {
      id: '/(private)/onboarding/create-workspace'
      path: '/create-workspace'
      fullPath: '/onboarding/create-workspace'
      preLoaderRoute: typeof privateOnboardingCreateWorkspaceRouteImport
      parentRoute: typeof privateOnboardingLayoutRoute
    }
    '/(private)/(app)/settings': {
      id: '/(private)/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof privateappSettingsRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(private)/(app)/creators': {
      id: '/(private)/(app)/creators'
      path: '/creators'
      fullPath: '/creators'
      preLoaderRoute: typeof privateappCreatorsRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(private)/(app)/campaigns': {
      id: '/(private)/(app)/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof privateappCampaignsRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(public)/campaigns/$campaignId/invite': {
      id: '/(public)/campaigns/$campaignId/invite'
      path: '/campaigns/$campaignId/invite'
      fullPath: '/campaigns/$campaignId/invite'
      preLoaderRoute: typeof publicCampaignsCampaignIdInviteRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/(app)/workspace/settings': {
      id: '/(private)/(app)/workspace/settings'
      path: '/workspace/settings'
      fullPath: '/workspace/settings'
      preLoaderRoute: typeof privateappWorkspaceSettingsRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(private)/(app)/influencer/$influencerId': {
      id: '/(private)/(app)/influencer/$influencerId'
      path: '/influencer/$influencerId'
      fullPath: '/influencer/$influencerId'
      preLoaderRoute: typeof privateappInfluencerInfluencerIdRouteImport
      parentRoute: typeof privateappLayoutRoute
    }
    '/(private)/(app)/campaigns/new': {
      id: '/(private)/(app)/campaigns/new'
      path: '/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof privateappCampaignsNewRouteImport
      parentRoute: typeof privateappCampaignsRoute
    }
    '/(private)/(app)/campaigns/$campaignId': {
      id: '/(private)/(app)/campaigns/$campaignId'
      path: '/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof privateappCampaignsCampaignIdRouteImport
      parentRoute: typeof privateappCampaignsRoute
    }
    '/(private)/(app)/campaigns/$campaignId/edit': {
      id: '/(private)/(app)/campaigns/$campaignId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof privateappCampaignsCampaignIdEditRouteImport
      parentRoute: typeof privateappCampaignsCampaignIdRoute
    }
    '/(private)/(app)/campaigns/$campaignId/influencer/$influencerId': {
      id: '/(private)/(app)/campaigns/$campaignId/influencer/$influencerId'
      path: '/influencer/$influencerId'
      fullPath: '/campaigns/$campaignId/influencer/$influencerId'
      preLoaderRoute: typeof privateappCampaignsCampaignIdInfluencerInfluencerIdRouteImport
      parentRoute: typeof privateappCampaignsCampaignIdRoute
    }
  }
}

interface privateappCampaignsCampaignIdRouteChildren {
  privateappCampaignsCampaignIdEditRoute: typeof privateappCampaignsCampaignIdEditRoute
  privateappCampaignsCampaignIdInfluencerInfluencerIdRoute: typeof privateappCampaignsCampaignIdInfluencerInfluencerIdRoute
}

const privateappCampaignsCampaignIdRouteChildren: privateappCampaignsCampaignIdRouteChildren =
  {
    privateappCampaignsCampaignIdEditRoute:
      privateappCampaignsCampaignIdEditRoute,
    privateappCampaignsCampaignIdInfluencerInfluencerIdRoute:
      privateappCampaignsCampaignIdInfluencerInfluencerIdRoute,
  }

const privateappCampaignsCampaignIdRouteWithChildren =
  privateappCampaignsCampaignIdRoute._addFileChildren(
    privateappCampaignsCampaignIdRouteChildren,
  )

interface privateappCampaignsRouteChildren {
  privateappCampaignsCampaignIdRoute: typeof privateappCampaignsCampaignIdRouteWithChildren
  privateappCampaignsNewRoute: typeof privateappCampaignsNewRoute
}

const privateappCampaignsRouteChildren: privateappCampaignsRouteChildren = {
  privateappCampaignsCampaignIdRoute:
    privateappCampaignsCampaignIdRouteWithChildren,
  privateappCampaignsNewRoute: privateappCampaignsNewRoute,
}

const privateappCampaignsRouteWithChildren =
  privateappCampaignsRoute._addFileChildren(privateappCampaignsRouteChildren)

interface privateappLayoutRouteChildren {
  privateappCampaignsRoute: typeof privateappCampaignsRouteWithChildren
  privateappCreatorsRoute: typeof privateappCreatorsRoute
  privateappSettingsRoute: typeof privateappSettingsRoute
  privateappIndexRoute: typeof privateappIndexRoute
  privateappInfluencerInfluencerIdRoute: typeof privateappInfluencerInfluencerIdRoute
  privateappWorkspaceSettingsRoute: typeof privateappWorkspaceSettingsRoute
}

const privateappLayoutRouteChildren: privateappLayoutRouteChildren = {
  privateappCampaignsRoute: privateappCampaignsRouteWithChildren,
  privateappCreatorsRoute: privateappCreatorsRoute,
  privateappSettingsRoute: privateappSettingsRoute,
  privateappIndexRoute: privateappIndexRoute,
  privateappInfluencerInfluencerIdRoute: privateappInfluencerInfluencerIdRoute,
  privateappWorkspaceSettingsRoute: privateappWorkspaceSettingsRoute,
}

const privateappLayoutRouteWithChildren =
  privateappLayoutRoute._addFileChildren(privateappLayoutRouteChildren)

interface privateOnboardingLayoutRouteChildren {
  privateOnboardingCreateWorkspaceRoute: typeof privateOnboardingCreateWorkspaceRoute
  privateOnboardingVerifyPhoneRoute: typeof privateOnboardingVerifyPhoneRoute
  privateOnboardingWelcomeRoute: typeof privateOnboardingWelcomeRoute
  privateOnboardingIndexRoute: typeof privateOnboardingIndexRoute
}

const privateOnboardingLayoutRouteChildren: privateOnboardingLayoutRouteChildren =
  {
    privateOnboardingCreateWorkspaceRoute:
      privateOnboardingCreateWorkspaceRoute,
    privateOnboardingVerifyPhoneRoute: privateOnboardingVerifyPhoneRoute,
    privateOnboardingWelcomeRoute: privateOnboardingWelcomeRoute,
    privateOnboardingIndexRoute: privateOnboardingIndexRoute,
  }

const privateOnboardingLayoutRouteWithChildren =
  privateOnboardingLayoutRoute._addFileChildren(
    privateOnboardingLayoutRouteChildren,
  )

interface privateLayoutRouteChildren {
  privateappLayoutRoute: typeof privateappLayoutRouteWithChildren
  privateOnboardingLayoutRoute: typeof privateOnboardingLayoutRouteWithChildren
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateappLayoutRoute: privateappLayoutRouteWithChildren,
  privateOnboardingLayoutRoute: privateOnboardingLayoutRouteWithChildren,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicResetPasswordRoute: typeof publicResetPasswordRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
  publicCampaignsCampaignIdInviteRoute: typeof publicCampaignsCampaignIdInviteRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicResetPasswordRoute: publicResetPasswordRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
  publicCampaignsCampaignIdInviteRoute: publicCampaignsCampaignIdInviteRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
