/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './screens/__root'
import { Route as publicLayoutRouteImport } from './screens/(public)/_layout'
import { Route as privateLayoutRouteImport } from './screens/(private)/_layout'
import { Route as publicSignUpRouteImport } from './screens/(public)/sign-up'
import { Route as publicSignInRouteImport } from './screens/(public)/sign-in'
import { Route as publicForgotPasswordRouteImport } from './screens/(public)/forgot-password'
import { Route as privateOnboardingLayoutRouteImport } from './screens/(private)/onboarding/_layout'
import { Route as privateOnboardingIndexRouteImport } from './screens/(private)/onboarding/index'
import { Route as privateappIndexRouteImport } from './screens/(private)/(app)/index'

const publicLayoutRoute = publicLayoutRouteImport.update({
  id: '/(public)',
  getParentRoute: () => rootRouteImport,
} as any)
const privateLayoutRoute = privateLayoutRouteImport.update({
  id: '/(private)',
  getParentRoute: () => rootRouteImport,
} as any)
const publicSignUpRoute = publicSignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicSignInRoute = publicSignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => publicLayoutRoute,
} as any)
const publicForgotPasswordRoute = publicForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => publicLayoutRoute,
} as any)
const privateOnboardingLayoutRoute = privateOnboardingLayoutRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => privateLayoutRoute,
} as any)
const privateOnboardingIndexRoute = privateOnboardingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => privateOnboardingLayoutRoute,
} as any)
const privateappIndexRoute = privateappIndexRouteImport.update({
  id: '/(app)/',
  path: '/',
  getParentRoute: () => privateLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/onboarding': typeof privateOnboardingLayoutRouteWithChildren
  '/forgot-password': typeof publicForgotPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof privateappIndexRoute
  '/onboarding/': typeof privateOnboardingIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof publicForgotPasswordRoute
  '/sign-in': typeof publicSignInRoute
  '/sign-up': typeof publicSignUpRoute
  '/': typeof privateappIndexRoute
  '/onboarding': typeof privateOnboardingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(private)': typeof privateLayoutRouteWithChildren
  '/(public)': typeof publicLayoutRouteWithChildren
  '/(private)/onboarding': typeof privateOnboardingLayoutRouteWithChildren
  '/(public)/forgot-password': typeof publicForgotPasswordRoute
  '/(public)/sign-in': typeof publicSignInRoute
  '/(public)/sign-up': typeof publicSignUpRoute
  '/(private)/(app)/': typeof privateappIndexRoute
  '/(private)/onboarding/': typeof privateOnboardingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/onboarding'
    | '/forgot-password'
    | '/sign-in'
    | '/sign-up'
    | '/'
    | '/onboarding/'
  fileRoutesByTo: FileRoutesByTo
  to: '/forgot-password' | '/sign-in' | '/sign-up' | '/' | '/onboarding'
  id:
    | '__root__'
    | '/(private)'
    | '/(public)'
    | '/(private)/onboarding'
    | '/(public)/forgot-password'
    | '/(public)/sign-in'
    | '/(public)/sign-up'
    | '/(private)/(app)/'
    | '/(private)/onboarding/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  privateLayoutRoute: typeof privateLayoutRouteWithChildren
  publicLayoutRoute: typeof publicLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(public)': {
      id: '/(public)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof publicLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(private)': {
      id: '/(private)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof privateLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/sign-up': {
      id: '/(public)/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof publicSignUpRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/sign-in': {
      id: '/(public)/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof publicSignInRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(public)/forgot-password': {
      id: '/(public)/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof publicForgotPasswordRouteImport
      parentRoute: typeof publicLayoutRoute
    }
    '/(private)/onboarding': {
      id: '/(private)/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof privateOnboardingLayoutRouteImport
      parentRoute: typeof privateLayoutRoute
    }
    '/(private)/onboarding/': {
      id: '/(private)/onboarding/'
      path: '/'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof privateOnboardingIndexRouteImport
      parentRoute: typeof privateOnboardingLayoutRoute
    }
    '/(private)/(app)/': {
      id: '/(private)/(app)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof privateappIndexRouteImport
      parentRoute: typeof privateLayoutRoute
    }
  }
}

interface privateOnboardingLayoutRouteChildren {
  privateOnboardingIndexRoute: typeof privateOnboardingIndexRoute
}

const privateOnboardingLayoutRouteChildren: privateOnboardingLayoutRouteChildren =
  {
    privateOnboardingIndexRoute: privateOnboardingIndexRoute,
  }

const privateOnboardingLayoutRouteWithChildren =
  privateOnboardingLayoutRoute._addFileChildren(
    privateOnboardingLayoutRouteChildren,
  )

interface privateLayoutRouteChildren {
  privateOnboardingLayoutRoute: typeof privateOnboardingLayoutRouteWithChildren
  privateappIndexRoute: typeof privateappIndexRoute
}

const privateLayoutRouteChildren: privateLayoutRouteChildren = {
  privateOnboardingLayoutRoute: privateOnboardingLayoutRouteWithChildren,
  privateappIndexRoute: privateappIndexRoute,
}

const privateLayoutRouteWithChildren = privateLayoutRoute._addFileChildren(
  privateLayoutRouteChildren,
)

interface publicLayoutRouteChildren {
  publicForgotPasswordRoute: typeof publicForgotPasswordRoute
  publicSignInRoute: typeof publicSignInRoute
  publicSignUpRoute: typeof publicSignUpRoute
}

const publicLayoutRouteChildren: publicLayoutRouteChildren = {
  publicForgotPasswordRoute: publicForgotPasswordRoute,
  publicSignInRoute: publicSignInRoute,
  publicSignUpRoute: publicSignUpRoute,
}

const publicLayoutRouteWithChildren = publicLayoutRoute._addFileChildren(
  publicLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  privateLayoutRoute: privateLayoutRouteWithChildren,
  publicLayoutRoute: publicLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
